---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aap-agentic-server
  namespace: llama-stack
  labels:
    app: aap-agentic-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aap-agentic-server
  template:
    metadata:
      name: aap-agentic-server
      labels:
        app: aap-agentic-server
    spec:
      containers:
        - name: aap-agentic-server
          image: 'quay.io/rh-ee-dwaters/aap-agentic-server:latest'
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: LLAMASTACK_URL
              value: "http://llamastack-with-config-service.llama-stack.svc.cluster.local:8321" 
            - name: REMOTE_AAP_MCP_URL
              value: "http://route-mcp-server-aap-mcp.apps.cluster-z5r5g.z5r5g.sandbox1310.opentlc.com/sse"
            - name: LLAMASTACK_MODEL_ID
              value: "deepseek/deepseek-r1-0528-qwen3-8b-bnb-4bit"
---
kind: Service
apiVersion: v1
metadata:
  name: aap-agentic-server
  namespace: llama-stack
  labels:
    app: aap-agentic-server
spec:
  type: NodePort
  selector:
    app: aap-agentic-server
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-aap-agentic-server
  namespace: llama-stack
spec:
  path: /
  to:
    kind: Service
    name: aap-agentic-server
    weight: 100
  host: ''
  port:
    targetPort: http
  alternateBackends: []